on:
  push:
    tags:
      - '*'  # only test when a tag is pushed
concurrency:
  group: registries-tests

name: Test on tag
jobs:
  tests-integration-buildah:
    name: Integration tests with buildah
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Login to quay
        run: echo ${{ secrets.DOCKER_TESTING_PASSWORD }} | sudo -E docker login -u ${{ secrets.DOCKER_TESTING_USERNAME }} --password-stdin quay.io
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install -y upx && sudo -E env "PATH=$PATH" make deps
          sudo apt-get install -y buildah
      - name: Login to quay with buildah
        run: echo ${{ secrets.DOCKER_TESTING_PASSWORD }} | sudo buildah login -u ${{ secrets.DOCKER_TESTING_USERNAME }} --password-stdin quay.io
      - name: Tests with buildah backend
        run: |
          sudo -E env "PATH=$PATH" \
                  env "LUET_BACKEND=buildah" \
                  make test-integration
  tests-integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Login to quay
        run: echo ${{ secrets.DOCKER_TESTING_PASSWORD }} | sudo -E docker login -u ${{ secrets.DOCKER_TESTING_USERNAME }} --password-stdin quay.io
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install -y upx && sudo -E env "PATH=$PATH" make deps
      - name: Tests
        run: |
          sudo -E \
                env "PATH=$PATH" \
                env "TEST_DOCKER_IMAGE=${{ secrets.DOCKER_TESTING_IMAGE }}" \
                env "UNIT_TEST_DOCKER_IMAGE=${{ secrets.DOCKER_TESTING_IMAGE }}" \
                env "UNIT_TEST_DOCKER_IMAGE_REPOSITORY=${{ secrets.DOCKER_TESTING_UNIT_TEST_IMAGE }}" \
                make test-integration

  tests-unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Login to quay
        run: echo ${{ secrets.DOCKER_TESTING_PASSWORD }} | sudo -E docker login -u ${{ secrets.DOCKER_TESTING_USERNAME }} --password-stdin quay.io
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install -y upx && sudo -E env "PATH=$PATH" make deps
          sudo apt-get install -y buildah
          sudo make build
          sudo cp -rf luet /usr/bin/luet
      - name: Tests
        run: |
          sudo -E \
                env "PATH=$PATH" \
                env "TEST_DOCKER_IMAGE=${{ secrets.DOCKER_TESTING_IMAGE }}" \
                env "UNIT_TEST_DOCKER_IMAGE=${{ secrets.DOCKER_TESTING_IMAGE }}" \
                env "UNIT_TEST_DOCKER_IMAGE_REPOSITORY=${{ secrets.DOCKER_TESTING_UNIT_TEST_IMAGE }}" \
                make coverage
      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          file: coverage.txt
